from pydantic import BaseModel, Field

class ParkingBase(BaseModel):
    title: str = Field(..., description="Title of the parking")
    address: str = Field(..., description="Address of the parking")
    latitude: float = Field(..., description="Latitude of the parking location")
    longitude: float = Field(..., description="Longitude of the parking location")
    capacity: int = Field(..., description="Total capacity of the parking")
    available_spots: int = Field(..., description="Number of available spots in the parking")
    owner_id: int = Field(..., description="ID of the owner of the parking")

class ParkingCreateRequest(ParkingBase):
    """Request body for creating a parking."""
    pass

class ParkingCreateResponse(ParkingBase):
    """Response body for the created parking, with the ID generated by the database."""
    id: int = Field(..., description="Unique identifier of the parking")

class ParkingGetResponse(ParkingBase):
    """Response body for getting a parking by ID."""
    id: int = Field(..., description="Unique identifier of the parking")

class ParkingNearResponse(BaseModel):
    """Response body for getting parkings near a location."""
    parkings: list[ParkingGetResponse] = Field(..., description="List of parkings near the specified location")